# Generated by Django 5.0.3 on 2024-06-13 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa_app', '0006_historicalquestion_is_closed_question_is_closed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PageVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата посещения')),
                ('url', models.CharField(max_length=2048, verbose_name='URL')),
                ('query_params', models.TextField(verbose_name='GET параметры')),
                ('method', models.CharField(max_length=10, verbose_name='HTTP метод')),
                ('user_agent', models.CharField(max_length=256, verbose_name='User Agent')),
                ('os', models.CharField(max_length=100, verbose_name='Операционная система')),
                ('browser', models.CharField(max_length=100, verbose_name='Браузер')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Посещение страницы',
                'verbose_name_plural': 'Посещения страниц',
            },
        ),
    ]
